### ISSUE TITLE
[byu-user-info] Using wrong fallback fonts

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-theme-components#419]
# Description

```css
.my-custom-login-class a {
        color: white;
        font-family: 'HCo Ringside Narrow SSm', Helvetica, sans-serif;
        cursor: pointer;
}
```
That should be referencing Arial, not Helvetica. The is in the _Overriding Your CMS_ section.

# Websites Affected

http://2017-components-demo.cdn.byu.edu/byu-user-info.html

# Issue Type

*Is this (add an x in the boxes that apply)*

- [ ] A difference between the components and the [Official Specification](https://brand.byu.edu)?
- [ ] A bug, such as a Javascript error, or the UI not rendering properly
    on a page?
- [ ] Inconsistent appearance/behavior between browsers?
- [ ] An issue on mobile browsers?
- [ ] A request for a new feature/enhancement?

# Browsers Affected

*Add an x in all the boxes that apply. Please mark desktop and mobile
browsers separately.*

**We support the last two versions of Chrome, Firefox, Safari, and Edge.**

## Desktop Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Apple Safari
- [ ] Microsoft Edge
- [ ] Other (please specify)

## Mobile Browsers

- [ ] Any browser on iOS
- [ ] Chrome for Android
- [ ] Firefox Mobile for Android
- [ ] Other (please specify)

# Web Site Platform

*What is hosting your website?*

- [ ] Drupal 7
- [ ] Drupal 8
- [ ] Wordpress
- [ ] Custom Site
- [ ] Don't Know
